version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: qg_jobs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./internal/store/schema.sql:/app/internal/store/schema.sql:ro

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  job-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=qg_jobs
      - REDIS_ADDR=redis:6379
    depends_on:
      - postgres
      - redis

  appwright-agent:
    build: .
    environment:
      - BROWSERSTACK_USERNAME=${BROWSERSTACK_USERNAME}
      - BROWSERSTACK_ACCESS_KEY=${BROWSERSTACK_ACCESS_KEY}
    command: ["./appwright-agent", "--server=job-server:8080"]
    depends_on:
      - job-server

volumes:
  postgres_data:
